#!/usr/bin/env bash
#
# Executive Dashboard Setup
# Generated by atlas-kit for [EXECUTIVE_NAME] at [COMPANY_NAME]
#
# This script:
#   1. Installs npm dependencies and builds the dashboard
#   2. Seeds the auth database with your credentials
#   3. Creates a systemd service
#   4. Optionally configures a Caddy reverse proxy
#
# Run from the dashboard source directory:
#   bash dashboard-setup.local.sh
#
# Prerequisites:
#   - Node.js 22+ and npm
#   - sqlite3 CLI
#   - systemd (for the service)
#   - Caddy (optional, for HTTPS reverse proxy)

set -euo pipefail

# --- Config (filled by atlas-kit install) ---
WORKSPACE_PATH="[WORKSPACE_PATH]"
DASHBOARD_PORT="[DASHBOARD_PORT]"
AGENT_NAME="[AGENT_NAME]"
APP_NAME="[AGENT_NAME]'s Dashboard"
ORG_NAME="[COMPANY_NAME]"
DASHBOARD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/kit/dashboard/app/source"

# --- Verify prerequisites ---
echo "=== Executive Dashboard Setup ==="
echo

command -v node >/dev/null 2>&1 || { echo "ERROR: Node.js not found. Install Node.js 22+."; exit 1; }
command -v npm >/dev/null 2>&1 || { echo "ERROR: npm not found."; exit 1; }
command -v sqlite3 >/dev/null 2>&1 || { echo "ERROR: sqlite3 not found. Install with: sudo apt install sqlite3"; exit 1; }

echo "Node: $(node --version)"
echo "Dashboard dir: $DASHBOARD_DIR"
echo "Workspace: $WORKSPACE_PATH"
echo "Port: $DASHBOARD_PORT"
echo

# --- Phase 1: Generate session secret ---
echo "=== Phase 1: Session secret ==="
SESSION_SECRET=$(openssl rand -hex 32)
echo "Generated session secret."

# --- Phase 2: Seed auth database ---
echo
echo "=== Phase 2: Auth setup ==="
AUTH_DB="$WORKSPACE_PATH/db/auth.db"

if [ ! -f "$AUTH_DB" ]; then
  echo "ERROR: auth.db not found at $AUTH_DB"
  echo "Make sure the db/auth component was installed first."
  exit 1
fi

echo "Creating your dashboard login."
read -rp "Email address: " AUTH_EMAIL
while true; do
  read -rsp "Password: " AUTH_PASSWORD
  echo
  read -rsp "Confirm password: " AUTH_CONFIRM
  echo
  if [ "$AUTH_PASSWORD" = "$AUTH_CONFIRM" ]; then
    break
  fi
  echo "Passwords don't match. Try again."
done

# Hash password with bcryptjs via Node.js
HASH=$(node -e "
  const bcrypt = require('$DASHBOARD_DIR/node_modules/bcryptjs');
  const hash = bcrypt.hashSync(process.argv[1], 10);
  process.stdout.write(hash);
" "$AUTH_PASSWORD")

sqlite3 "$AUTH_DB" "INSERT OR REPLACE INTO users (id, email, password_hash, full_name, role, created_at) VALUES (1, '$AUTH_EMAIL', '$HASH', '[EXECUTIVE_NAME]', 'admin', datetime('now'));"
echo "Auth user created: $AUTH_EMAIL"

# --- Phase 3: Install and build ---
echo
echo "=== Phase 3: Install and build ==="
cd "$DASHBOARD_DIR"
npm install --production=false
npm run build
echo "Dashboard built successfully."

# --- Phase 4: Write .env.local ---
echo
echo "=== Phase 4: Environment config ==="
cat > "$DASHBOARD_DIR/.env.local" <<EOF
WORKSPACE_PATH=$WORKSPACE_PATH
SESSION_SECRET=$SESSION_SECRET
SESSION_COOKIE_NAME=ea-dashboard-session
SESSION_DURATION_DAYS=30
NEXT_PUBLIC_APP_NAME=$APP_NAME
NEXT_PUBLIC_ORG_NAME=$ORG_NAME
PORT=$DASHBOARD_PORT
NODE_ENV=production
EOF
echo "Wrote .env.local"

# --- Phase 5: Create systemd service ---
echo
echo "=== Phase 5: Systemd service ==="
SERVICE_NAME="dashboard-$AGENT_NAME"
SERVICE_FILE="/etc/systemd/system/$SERVICE_NAME.service"

sudo tee "$SERVICE_FILE" > /dev/null <<EOF
[Unit]
Description=Executive Dashboard — $AGENT_NAME
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$DASHBOARD_DIR
ExecStart=$(which npx) next start -p $DASHBOARD_PORT -H 127.0.0.1
Restart=on-failure
RestartSec=5
Environment=NODE_ENV=production
Environment=PORT=$DASHBOARD_PORT
Environment=WORKSPACE_PATH=$WORKSPACE_PATH
Environment=SESSION_SECRET=$SESSION_SECRET
Environment=SESSION_COOKIE_NAME=ea-dashboard-session
Environment=SESSION_DURATION_DAYS=30
Environment=NEXT_PUBLIC_APP_NAME=$APP_NAME
Environment=NEXT_PUBLIC_ORG_NAME=$ORG_NAME

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl start "$SERVICE_NAME"
echo "Service $SERVICE_NAME started on port $DASHBOARD_PORT"

# --- Phase 6: Optional reverse proxy ---
echo
read -rp "Set up Caddy reverse proxy for HTTPS? [y/N] " SETUP_CADDY
if [[ "$SETUP_CADDY" =~ ^[Yy] ]]; then
  read -rp "Domain name (e.g. dashboard.example.com): " DOMAIN
  CADDY_CONF="/etc/caddy/clients/${AGENT_NAME}.caddy"
  sudo mkdir -p /etc/caddy/clients
  sudo tee "$CADDY_CONF" > /dev/null <<EOF
$DOMAIN {
    reverse_proxy localhost:$DASHBOARD_PORT
}
EOF
  sudo systemctl reload caddy
  echo "Caddy configured: https://$DOMAIN -> localhost:$DASHBOARD_PORT"
  echo
  echo "Make sure your DNS has an A record for $DOMAIN pointing to this server."
else
  echo "Skipped. Dashboard accessible at http://localhost:$DASHBOARD_PORT (Tailscale only)."
fi

# --- Done ---
echo
echo "=== Setup complete ==="
echo "Dashboard: http://localhost:$DASHBOARD_PORT"
echo "Login: $AUTH_EMAIL"
echo "Service: systemctl status $SERVICE_NAME"
